### ISSUE TITLE
Why are Expander's fields private?

### ISSUE THREAD

**Issue by mindreader** [fancy-regex/fancy-regex#113]
I want to use a slightly different expansion method, the default, but with `allow_undelimited_name: false`, but I can't see a way to do it with the public api available.

**Comment by keith-hall** [comment]
I would guess that the idea is to only expose things we know will be used, because once something is public we need to be more careful when making changes etc. and support various previously unthought of interactions.

I'd say open a PR, and then we can get more of an idea of how much maintenance burden it could add.
