### ISSUE TITLE
One match being returned twice instead of two different matches

### ISSUE THREAD

**Issue by panther99** [fancy-regex/fancy-regex#48]
I'm trying to find the matches for the following regular expression (basically everything between `{#` and `}`):

```
(?<={#)(.*?)(?=})
```

However, instead of getting both matches for the example below, I get two matches with the content of the first match.

```rs
let input = String::from("{#test1} {#test2}");
let re = Regex::new("(?<={#)(.*?)(?=})").unwrap();

let input_string_slice = &input.clone();
let result = re.captures(input_string_slice);

let captures = result.expect("Error during regex parsing").expect("No match found");
let first_match = captures.get(1).expect("No group");
let second_match = captures.get(2).expect("No group"); // panics
println!("{} {}", first_match.as_str(), second_match.as_str());
```

[Here](https://stackoverflow.com/questions/62487304/fancy-regex-not-returning-all-matches-in-the-input) is a question on StackOverflow where user Kitsu also posted the code which proves this. At first I thought I forgot to put global match so I'm only getting the first match, but by browsing the documentation I realized that's not the case.

**Comment by keith-hall** [comment]
I'm a little confused, but maybe I'm just misunderstanding something :)

You've got one capture group in your regex pattern. Surely you need to run the regex VM multiple times, once starting at position 0, then again starting at the end of the previous match until you find no more matches... instead of trying to access a non-existent second capture group?

```sh
cargo run --example toy -- run '(?<={#)(.*?)(?=})' '{#test1} {#test2}' 0
```

> captures: 0:[2..7] "test1" 1:[2..7] "test1"
iterate Some(Match { text: "{#test1} {#test2}", start: 2, end: 7 })
iterate Some(Match { text: "{#test1} {#test2}", start: 2, end: 7 })


```sh
cargo run --example toy -- run '(?<={#)(.*?)(?=})' '{#test1} {#test2}' 7
```
> captures: 0:[11..16] "test2" 1:[11..16] "test2"
iterate Some(Match { text: "{#test1} {#test2}", start: 11, end: 16 })
iterate Some(Match { text: "{#test1} {#test2}", start: 11, end: 16 })

**Comment by panther99** [comment]
> Surely you need to run the regex VM multiple times

Not sure if I understood you here - I need to check for the matches multiple times remembering last positions of the previous matches? 

Honestly I don't have much experience using regular expression libraries but I would expect to get all the matches in one pass, without having to do it multiple times.

**Comment by robinst** [comment]
Thanks @keith-hall, for helping out :). Yeah, Keith is right, you need to match multiple times to get all matches.

With the regex crate, you would use [captures_iter](https://docs.rs/regex/1.3.9/regex/struct.Regex.html#method.captures_iter) for that. fancy-regex doesn't have that API yet, so you currently need to use [captures_from_pos](https://docs.rs/fancy-regex/0.3.5/fancy_regex/struct.Regex.html#method.captures_from_pos) multiple times.

**Comment by panther99** [comment]
I understand now. Thanks for the help.
