### ISSUE TITLE
Support for BranchReset

### ISSUE THREAD

**Issue by lizelive** [fancy-regex/fancy-regex#82]
https://www.regular-expressions.info/branchreset.html

**Comment by robinst** [comment]
Hey! Sounds like something that should not be too hard to implement with the current architecture. It might mean that we can't delegate the expression inside `(?|...)` to the regex crate, but that's ok.

Looking at [Oniguruma's docs](https://github.com/kkos/oniguruma/blob/master/doc/RE), it looks like it doesn't implement this?

**Comment by keith-hall** [comment]
Thinking out loud here - is there a possibility to implement this by delegating the whole expression inside `(?|...)` and then renumbering the capture groups afterwards - assuming there are no backreferences referring to those groups of course? It feels like it should have best performance.

But I guess as we'd need to maintain the code for when there *are* backreferences, it might not make sense to have 2 implementations? Plus it could also affect behavior of when the branch reset group is repeated... (haven't thought about this much yet.)

Let's say that we don't delegate the inner expression then, how could we go about this? I think it should be possible to do the work at analyze/compile time and not need any changes in the VM. When we encounter the branch reset group, we could store the next capture group number, and then when visiting the Alt `|`, we reset the capture group number. After the end of the branch reset group, we set the next capture group number to the "next capture group number at the start of the group" + the highest count of capture groups which were in a branch. Does that sound reasonable or am I missing something? :)

**Comment by robinst** [comment]
> Thinking out loud here - is there a possibility to implement this by delegating the whole expression inside (?|...) and then renumbering the capture groups afterwards - assuming there are no backreferences referring to those groups of course? It feels like it should have best performance.

Yeah that should work. Currently for a `Delegate`, we record `start_group` and `end_group` which we use to shift the group positions. We'd have to change that to a `HashMap<usize, usize>` where we map each group number from the resulting match to where we want to save it to.

> But I guess as we'd need to maintain the code for when there are backreferences, it might not make sense to have 2 implementations?

On first reading I was confused why backreferences mattered, but you mean when there's a backref within a capturing group? In that case we already can't delegate the expression, right? Or can you make an example for what the problem is with backreferences?

> Does that sound reasonable or am I missing something? :)

Yep, sounds reasonable.

But before we implement this, I want to take a step back though and consider if we actually *want* to add support for branch reset. So far, we've had the goal of staying pretty close to Oniguruma's functionality. Oniguruma [doesn't support branch reset](https://github.com/kkos/oniguruma/blob/master/doc/RE). PCRE and derivates do, but I'm not convinced it's worth it. The regex crate rejected it [here](https://github.com/rust-lang/regex/issues/740). Thoughts?

**Comment by keith-hall** [comment]
> On first reading I was confused why backreferences mattered, but you mean when there's a backref within a capturing group? In that case we already can't delegate the expression, right? Or can you make an example for what the problem is with backreferences?

I was thinking with a pattern like `(?'before'x)(?|abc|(?'left'd)(?'middle'e)(?'right'f)|g(h)\2)(?'after'y)` - with a backref inside the branch reset group. It should match `xghhy`. But if we delegate the whole branch reset group, `\2` would not refer to `(h)`. But maybe we can renumber those backreferences also?

About whether we want to implement this, good question. My thinking was we *can* implement it without sacrificing any oniguruma compatibility, so I didn't see why we shouldn't. But if our goal is to be a safe Oniguruma "clone", then it would make sense to hold off until Oniguruma has this functionality. I didn't see any requests for such a feature on their issue tracker, so I'm not sure if that would ever happen.

**Comment by robinst** [comment]
Ok so the `\2` is inside the branch reset group, that means the whole alt wouldn't be delegated (because backrefs are hard). Which means we'd run them on the VM, which means by the time we look at `\2`, we should have the right capture group stored already.

Yeah. @lizelive did you have a pressing need for this or was it mostly for convenience? I'm leaning towards not implementing it for now (can reopen if we decide otherwise).
