### ISSUE TITLE
Support for Keep out \K

### ISSUE THREAD

**Issue by F34th3R** [fancy-regex/fancy-regex#87]
There is a method for this, without using lookbehind?

**Comment by robinst** [comment]
That's not currently supported, no. Here's a good reference for what it does and how it works: https://www.regular-expressions.info/keep.html

I've added the labels for feature request and help wanted, and I'd be happy if someone wanted to take a stab at implementing this. It doesn't sound too hard to implement, and I can outline what would need to be done if anyone shows interest in picking this up.

**Comment by robinst** [comment]
Cool :)! Yep, I'm pretty sure it has to be done at runtime. I think it would involve roughly:

1. Parsing `\K` and creating an `Expr` for it and making sure the corresponding expression is marked as "hard" so that we won't try to delegate it to the regex crate. We can probably still delegate things before and after it to regex, but I haven't put much thought into that part yet.
2. In the VM, whenever we encounter a `\K` instruction, store the position as the match (group 0) start position (might have to keep track of the original as well so we can properly resume matching, not sure off the top of my head). That should just work for subexpressions and repetitions.

There's probably some special cases (e.g. can't be used within lookarounds) that we need to handle too, but yeah.

**Comment by robinst** [comment]
@F34th3R Check out the 0.9.0 release which now includes support for `\K`, thanks to @keith-hall!
